### ISSUE TITLE
Clustering algorithm

### ISSUE THREAD

**Issue by IceYoshi** [IceYoshi/UAV-Sim#2]
Implement the clustering algorithm as described in the doc. If necessary, modify it to make it more optimized/functional. Test with random number of UAVs to see if it works for all cases.

**Comment by dren413** [comment]
Runs KHOPCA together with our clustering algorithm.
- Initially, all dUAV's flock and don't accept children.
- As soon as a dUAV becomes cluster-head (CH), it stops flocking and
starts accepting children until it reaches the desired number of
branches.
- Having gathered enough children, thus having enough branches, each
child starts accepting children.
- As soon as one child accepts exactly one child, it immediately stops
accepting further children and notfies the parent, which itself notfies
his parent etc. until reaching the CH.
- The CH checks if he the number of notifications = the number of
branches. If so, all leaves can start accepting further children (=1).
- Repeat whole process.


If a dUAV decides, due to KHOPCA, to give up his role as CH, all children will be discarded recursively, thus destroying the cluster. All members of that cluster, including the former CH, will then again start flocking and searching for other clusters.
